version: '3'
volumes:
    db:
networks:
    test_net:
services:
    web:
        image: nginx:latest
        ports:
            - '80:80'
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./:/app
        networks:
            - test_net
        depends_on:
            - php
        restart: always
    php:
        build:
            context: ./docker/php
        volumes:
            - ./:/app
        expose:
            - 9000
        networks:
            - test_net
        depends_on:
            - mysql
        restart: always
    mysql:
        image: mysql:5.7
        environment:
            TZ: ${WORKSPACE_TIMEZONE}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db:/var/lib/mysql
        ports:
            - ${DB_PORT}:3306
        networks:
            - test_net
        restart: always
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: 'mysql'
        ports:
            - '8080:80'
        networks:
            - test_net
        depends_on:
            - mysql
        restart: always
